"""Deterministic replay bundle synthesis for security observations."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any


class MinimalReproducerSynthesizer:
    """Build a replay-oriented bundle without fuzzing or runtime expansion."""

    schema = "minimal_reproducer_bundle_v1"

    def build(
        self,
        seed_context: Mapping[str, Any],
        security_candidate: Mapping[str, Any],
    ) -> dict[str, Any]:
        seed_id = str(seed_context.get("seed_id") or seed_context.get("seed_candidate_id") or "unknown_seed")
        family = str(seed_context.get("family") or seed_context.get("framework_family") or "unknown_family")
        libraries = _required_libraries(seed_context, security_candidate)
        break_type = _semantic_break_type(security_candidate)
        minimal_reproducer_c = _render_minimal_reproducer_c(seed_id, family, libraries, break_type)
        repro_steps = {
            "schema": "repro_steps_v1",
            "mode": "deterministic_seed_replay",
            "seed_id": seed_id,
            "family": family,
            "steps": [
                "load the same seed bytes used by the existing seed registry entry",
                "run the generated harness once per target library",
                "record runtime and oracle observations with the existing pipeline fields",
                "compare semantic break type across target libraries",
            ],
            "fuzzing_required": False,
            "runtime_pressure_required": False,
            "candidate_queue_written": False,
        }
        dependency_manifest = {
            "schema": "dependency_manifest_v1",
            "target_libraries": libraries,
            "requires_seed_registry_entry": True,
            "requires_existing_render_profile": True,
            "requires_existing_oracle_dispatcher": True,
            "network_required": False,
            "glm_required": False,
            "rag_reindex_required": False,
        }
        return {
            "schema": self.schema,
            "minimal_reproducer.c": minimal_reproducer_c,
            "repro_steps.yaml": repro_steps,
            "dependency_manifest.yaml": dependency_manifest,
            "same_seed_replay": True,
            "deterministic_seed_replay": True,
            "cross_library_replay_ready": bool(libraries),
            "candidate_queue_written": False,
            "claim_level": "minimal_replay_material_only",
        }


def build(seed_context: Mapping[str, Any], security_candidate: Mapping[str, Any]) -> dict[str, Any]:
    """Build deterministic replay material for an existing security observation."""

    return MinimalReproducerSynthesizer().build(seed_context, security_candidate)


def _required_libraries(seed_context: Mapping[str, Any], security_candidate: Mapping[str, Any]) -> list[str]:
    raw = (
        seed_context.get("target_libraries")
        or seed_context.get("targets")
        or security_candidate.get("target_libraries")
        or []
    )
    if isinstance(raw, str):
        raw = [raw]
    if not isinstance(raw, list):
        raw = []
    normalized = [str(item) for item in raw]
    if not normalized:
        normalized = ["mbedtls", "wolfssl", "botan"]
    return sorted(dict.fromkeys(normalized))


def _semantic_break_type(security_candidate: Mapping[str, Any]) -> str:
    flags = security_candidate.get("security_violation_flags") or []
    if isinstance(flags, list) and flags:
        return str(flags[0])
    summary = security_candidate.get("security_violation_summary")
    if isinstance(summary, Mapping):
        summary_flags = summary.get("security_violation_flags")
        if isinstance(summary_flags, list) and summary_flags:
            return str(summary_flags[0])
    return "security_relevant_inconsistency"


def _render_minimal_reproducer_c(
    seed_id: str,
    family: str,
    libraries: list[str],
    break_type: str,
) -> str:
    library_list = ", ".join(libraries)
    return f"""/*
 * Deterministic replay skeleton generated by the seed-driven pipeline.
 * It is intentionally a minimal replay scaffold, not a fuzz driver.
 * seed_id: {seed_id}
 * family: {family}
 * target_libraries: {library_list}
 * semantic_break_type: {break_type}
 */
#include <stdio.h>
#include <stddef.h>

#ifndef TARGET_LIBRARY
#define TARGET_LIBRARY "unset"
#endif

static const unsigned char seed_payload[] = {{
    /* The concrete bytes are loaded by the existing seed registry/render stage. */
    0x00
}};

int main(void) {{
    const size_t input_len = sizeof(seed_payload);
    printf("target_library=%s\\n", TARGET_LIBRARY);
    printf("seed_id=%s\\n", "{seed_id}");
    printf("family=%s\\n", "{family}");
    printf("input_len=%zu\\n", input_len);
    return 0;
}}
"""
