from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from typing import Any

import yaml

from caller_audit.external_caller_discovery import ExternalCodeHit, MockExternalSearchProvider
from caller_audit.impactlift_router import run_impactlift_router
from utils.agent_provider import AgentProvider


ROOT = Path(__file__).resolve().parents[1]
CMAC_CANDIDATE = ROOT / "artifacts/caller_audit/cmac-caller-discovery-v1/cmac_candidate.yaml"


class RouterImpactProvider(AgentProvider):
    def __init__(self) -> None:
        self.candidate_id = ""

    @property
    def name(self) -> str:
        return "router-test-impact-provider"

    @property
    def metadata(self) -> dict[str, object]:
        return {"backend": "unit-test"}

    def analyze(self, context_pack: dict[str, Any]) -> dict[str, Any]:
        self.candidate_id = str(context_pack["candidate_id"])
        return {
            "candidate_id": self.candidate_id,
            "summary": "Post-processing exploration artifact generated by unit test provider.",
            "findings": ["Caller evidence was preserved for downstream review."],
            "evidence": ["candidate_context_pack"],
            "confidence": "low",
            "caller_chain": [],
            "guards": [],
            "propagation": {},
            "unknowns": ["No post-processing claim was made."],
        }

    def analyze_structured(
        self,
        *,
        task: str,
        result_json_schema: dict[str, Any],
        output_stem: str,
    ) -> dict[str, Any]:
        del task, result_json_schema
        if output_stem == "exploitability":
            return {
                "candidate_id": self.candidate_id,
                "summary": "Unit test assessment placeholder.",
                "input_sources": [],
                "attacker_control": [],
                "trust_boundaries": [],
                "security_usage": [],
                "reachable_paths": [],
                "barriers": [],
                "unknowns": ["Not evaluated by router test."],
                "evidence": ["impact_exploration.yaml"],
                "exploitability_assessment": "unknown",
                "confidence": "low",
            }
        if output_stem == "security_impact":
            return {
                "candidate_id": self.candidate_id,
                "security_classification": "insufficient_evidence",
                "affected_security_properties": [],
                "impact_evidence": ["post-processing artifacts only"],
                "confidence": "low",
                "unknowns": ["Not evaluated by router test."],
            }
        raise AssertionError(f"unexpected output_stem: {output_stem}")


class ImpactLiftRouterTest(unittest.TestCase):
    def _write_yaml(self, root: Path, name: str, data: dict[str, Any]) -> Path:
        path = root / name
        path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
        return path

    def _cmac_hit(self) -> ExternalCodeHit:
        return ExternalCodeHit(
            repository_name="zhaozg/lua-openssl",
            repository_url="https://github.com/zhaozg/lua-openssl",
            file_path="src/mac.c",
            file_url="https://github.com/zhaozg/lua-openssl/blob/master/src/mac.c",
            fragments=(
                "EVP_MAC_update(ctx->ctx, data, data_len);\n"
                "EVP_MAC_final(ctx->ctx, out, &out_len, out_size);",
            ),
        )

    def test_unknown_caller_candidate_runs_discovery_and_impactlift(self):
        candidate_text = CMAC_CANDIDATE.read_text(encoding="utf-8")
        self.assertNotIn("lua-openssl", candidate_text)
        self.assertNotIn("zhaozg", candidate_text)

        provider = MockExternalSearchProvider(
            {
                '"EVP_MAC_update" "EVP_MAC_final" CMAC': [self._cmac_hit()],
                '"EVP_MAC_update" "EVP_MAC_final"': [self._cmac_hit()],
            }
        )
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            outputs = run_impactlift_router(
                CMAC_CANDIDATE,
                output_root=root / "run",
                impact_provider=RouterImpactProvider(),
                external_provider=provider,
                evidence_roots=[],
                workspace_roots=[],
                allow_needs_review=True,
            )
            summary = yaml.safe_load(outputs["summary_path"].read_text(encoding="utf-8"))
            context_pack = yaml.safe_load(outputs["candidate_context_pack"].read_text(encoding="utf-8"))

        self.assertEqual(summary["status"], "completed")
        self.assertTrue(summary["route"]["caller_discovery"])
        self.assertFalse(summary["route"]["known_caller"])
        self.assertEqual(summary["stages"]["caller_discovery"]["status"], "completed")
        self.assertEqual(summary["stages"]["impact_exploration"]["status"], "completed")
        self.assertEqual(summary["stages"]["exploitability"]["status"], "completed")
        self.assertEqual(summary["stages"]["security_impact"]["status"], "completed")
        self.assertTrue(any(repo["name"] == "zhaozg/lua-openssl" for repo in summary["discovered_callers"]))
        self.assertTrue(
            any(
                site["repository"] == "zhaozg/lua-openssl" and site["file"] == "src/mac.c"
                for site in context_pack["caller_discovery_evidence"]["call_sites"]
            )
        )
        self.assertEqual(summary["final_assessment"], "insufficient_evidence")
        dumped = yaml.safe_dump(summary).lower() + yaml.safe_dump(context_pack).lower()
        self.assertNotIn("vulnerability: true", dumped)
        self.assertNotIn("cve-", dumped)
        self.assertEqual(summary["claim_policy"]["vulnerability"], "not_assessed_by_runner")
        self.assertEqual(summary["claim_policy"]["cve"], "not_assessed_by_runner")

    def test_ineligible_candidate_is_skipped(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            candidate = self._write_yaml(
                root,
                "candidate.yaml",
                {
                    "candidate_id": "safe-baseline",
                    "library": "OpenSSL",
                    "family": "parser_full_consumption_oracle",
                    "api": ["openssl x509"],
                    "classification": "safe_reject",
                    "observed_behavior": "expected reject",
                },
            )
            outputs = run_impactlift_router(
                candidate,
                output_root=root / "run",
                impact_provider=RouterImpactProvider(),
            )
            summary = yaml.safe_load(outputs["summary_path"].read_text(encoding="utf-8"))

        self.assertEqual(summary["status"], "skipped_ineligible")
        self.assertEqual(summary["stages"]["caller_discovery"]["status"], "not_run")
        self.assertEqual(summary["stages"]["impact_exploration"]["status"], "not_run")

    def test_known_caller_candidate_does_not_run_discovery(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            candidate = self._write_yaml(
                root,
                "known.yaml",
                {
                    "candidate_id": "known-caller-candidate",
                    "library": "OpenSSL",
                    "family": "parser_full_consumption_oracle",
                    "api": ["d2i_X509"],
                    "classification": "semantic_gap_candidate",
                    "observed_behavior": "candidate requires post-processing",
                    "repository": {"name": "example/repo", "url": "https://example.invalid/repo"},
                },
            )
            outputs = run_impactlift_router(
                candidate,
                output_root=root / "run",
                impact_provider=RouterImpactProvider(),
            )
            summary = yaml.safe_load(outputs["summary_path"].read_text(encoding="utf-8"))

        self.assertTrue(summary["route"]["known_caller"])
        self.assertFalse(summary["route"]["caller_discovery"])
        self.assertEqual(summary["stages"]["caller_discovery"]["status"], "not_run_known_caller")
        self.assertIsNone(outputs["caller_discovery"])
        self.assertEqual(summary["status"], "completed")

    def test_mainline_candidate_queue_item_can_enter_router(self):
        queue = ROOT / "artifacts/cross_library/mainline/batch_connect_existing_oracle_results_v1/candidate_queue.yaml"
        data = yaml.safe_load(queue.read_text(encoding="utf-8"))
        candidate_id = data["items"][0]["input_id"]

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            outputs = run_impactlift_router(
                queue,
                candidate_id=candidate_id,
                output_root=root / "run",
                impact_provider=RouterImpactProvider(),
                evidence_roots=[],
                workspace_roots=[],
            )
            summary = yaml.safe_load(outputs["summary_path"].read_text(encoding="utf-8"))

        self.assertEqual(summary["candidate_id"], candidate_id)
        self.assertEqual(summary["status"], "completed")
        self.assertTrue(summary["route"]["caller_discovery"])
        self.assertEqual(summary["stages"]["security_impact"]["status"], "completed")


if __name__ == "__main__":
    unittest.main()
