schema: compile_run_environment_v1
generated_at: '2026-06-11T16:38:54+00:00'
openssl_install: /home/wen/work/install-openssl-3.5.5-asan
include_dir: /home/wen/work/install-openssl-3.5.5-asan/include
include_dir_exists: true
lib_dir: /home/wen/work/install-openssl-3.5.5-asan/lib64
lib_dir_exists: true
openssl_binary: /home/wen/work/install-openssl-3.5.5-asan/bin/openssl
openssl_binary_exists: true
openssl_modules: /home/wen/work/install-openssl-3.5.5-asan/lib64/ossl-modules
openssl_modules_exists: true
gcc: /usr/bin/gcc
timeout_seconds: 10
asan_options: detect_leaks=0:abort_on_error=1:symbolize=1
ubsan_options: halt_on_error=1:print_stacktrace=1
